create table inputs
(
    id                     varchar(30) not null
        constraint inputs_pk
            primary key,
    type                   varchar(50),
    caption                jsonb,
    required               boolean default false,
    placeholder            varchar(50),
    tooltip                varchar(100),
    default_value          varchar(100),
    have_static_data       boolean,
    refillable             boolean default false,
    refillable_source      varchar(50),
    updaters               jsonb,
    additional_regulations jsonb
);

comment on column inputs.have_static_data is 'ключ источника данных';

alter table inputs
    owner to postgres;

INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('issuing_authority', 'textbox', '{"kg": "Документти берген мекеме", "ru": "Орган выдавший документ"}', true, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('district_uuid', 'selectbox', '{"kg": "Район", "ru": "Район"}', true, null, '', 'Не выбрано', true, true, '/api/getDistricts', '[{"as": "regionId", "event": "change", "component_id": "region_uuid"}]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('locality_uuid', 'selectbox', '{"kg": "Калктуу пункт", "ru": "Населенный пункт"}', true, null, '', 'Не выбрано', false, true, '/api/getCities', '[{"as": "districtId", "event": "change", "component_id": "district_uuid"}]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('passport_series_uuid', 'selectbox', '{"kg": "Паспортунун номери", "ru": "Серия паспорта"}', true, null, '', 'Не выбрано', true, true, '/api/getPassportSeries', '[]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('building_type_uuid', 'selectbox', '{"kg": "Тип здания", "ru": "Тип здания"}', true, null, '', 'Не выбрано', true, true, '/api/getBuildingTypes', '[]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('gender', 'selectbox', '{"kg": "Жынысы", "ru": "Пол"}', true, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('contact_number', 'textbox', '{"kg": "Байланыш номери", "ru": "Контактный номер"}', false, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('housing_type', 'selectbox', '{"kg": "Турак жайдын түрү", "ru": "Тип жилья"}', false, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('passport_num', 'textbox', '{"kg": "Паспортунун номери", "ru": "Номер паспорта"}', false, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('technical_conditions', 'selectbox', '{"kg": "Техникалык шарттар", "ru": "Технические условия"}', true, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('region_uuid', 'selectbox', '{"kg": "Регион", "ru": "Регион"}', true, null, '', 'Не выбрано', true, true, '/api/getRegions', '[]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('name', 'textbox', '{"kg": "Аты", "ru": "Имя"}', true, null, '', null, null, false, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('scan_those_home_passports', 'filebox', '{"kg": "Сканерленген үйдүн тех.паспорту", "ru": "Скан. тех. паспорта на дом"}', true, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('scan_passports', 'filebox', '{"kg": "Сканерленген паспорту", "ru": "Скан. паспорта"}', true, null, '', 'Не выбрано', true, true, null, null, '{"maxSize": 5000000}');
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('fname', 'textbox', '{"kg": "Атасынын аты", "ru": "Отчество"}', true, 'Введите свое отчество', '', null, null, false, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('additional_number', 'textbox', '{"kg": "Кошумча номер", "ru": "Дополнительный номер"}', true, null, '', null, true, true, null, null, '{"mask": "+996(###)##-##-##"}');
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('region_jira', 'selectbox', '{"kg": "Регион", "ru": "Регион"}', true, null, '', 'Не выбрано', true, false, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('house_number', 'textbox', '{"kg": "Үйдүн номери", "ru": "Номер дома"}', true, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('jl_comment', 'textbox', '{"kg": "Комментарий", "ru": "Комментарий"}', true, null, 'Опишите жалобу', null, false, false, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('sname', 'textbox', '{"kg": "Фамилиясы", "ru": "Фамилия"}', true, null, '', null, null, false, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('email', 'textbox', '{"kg": "Электрондук дареги", "ru": "Электронный адрес"}', false, null, '', null, true, true, null, null, '{"regex": "^[\\w_\\.\\-]{1,50}@[\\w\\-]{1,30}.[\\w]{1,10}$"}');
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('installation_contractors', 'selectbox', '{"kg": "Монтаж иштеринин аткаруучулары", "ru": "Исполнители монтажных работ"}', false, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('gas_consumption_pattern', 'selectbox', '{"kg": "Жаратылыш газын колдонуу багыты", "ru": "Характер потребления газа"}', false, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('planned_gas-using_devices', 'selectbox', '{"kg": "Пландалып жаткан газ колдонуучу шаймандар", "ru": "Планируемые газоиспользующие приборы"}', false, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('invest_program', 'selectbox', '{"kg": "Инвест программа", "ru": "Инвест программа"}', false, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('date_of_issue_of_the_document', 'textbox', '{"kg": "Документ берилген күн", "ru": "Дата выдачи документа"}', false, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('sector_type_uuid', 'selectbox', '{"kg": "Тип сектора", "ru": "Тип сектора"}', true, null, '', 'Не выбрано', true, true, '/api/getSectorTypes', '[]', null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('account', 'textbox', '{"kg": "Өздүк эсеп", "ru": "Лицевой счет"}', true, null, '', null, true, true, null, null, '{"regex": "^[\\d]{9}$"}');
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('inn', 'textbox', '{"kg": "ИСН", "ru": "ИНН"}', true, null, '', null, true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('consent', 'checkbox', '{"kg": "Менин жеке маалыматымды иштеп чыгууга макулмун", "ru": "Я согласен на обработку персональных данных"}', true, null, '', 'Не выбрано', true, true, null, null, null);
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('birthday', 'textbox', '{"kg": "Туулган жылы", "ru": "Дата рождения"}', false, 'дд.мм.гггг', '', null, true, true, null, null, '{"regex": "^\\d{2}\\.\\d{2}\\.\\d{4}$"}');
INSERT INTO public.inputs (id, type, caption, required, placeholder, tooltip, default_value, have_static_data, refillable, refillable_source, updaters, additional_regulations) VALUES ('street_uuid', 'selectbox', '{"kg": "Көчөсү", "ru": "Улица"}', true, null, '', 'Не выбрано', false, true, '/api/getStreets', '[{"as": "cityIdORDistrictId", "event": "change", "component_id": "locality_uuid"}, {"as": "cityIdORDistrictId", "event": "change", "component_id": "district_uuid"}]', null);